 apiVersion: v1
 kind: ConfigMap
 metadata:
   name: incentive-scraper-configmap
   namespace: gds
 data:
   PUPPETTER_WS_ENDPOINT: 'ws://gds-laravel-browserless.gds:3000'
   QUEUE_HOST: 'gds-laravel-redis'
   QUEUE_PORT: '6379'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: incentive-scraper
  namespace: gds
spec:
  selector:
    matchLabels:
      app: incentive-scraper
  replicas: 1
  template:
    metadata:
      labels:
        app: incentive-scraper
    spec:
      containers:
        - name: app
          image: mokkahei24/incentive-scraper
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: incentive-scraper-configmap
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: incentive-scraper
  namespace: gds
  labels:
    app: incentive-scraper
spec:
  ports:
    - port: 3000
      protocol: TCP
  selector:
    app: incentive-scraper
